name: my_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+8
  http: ^0.13.5
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  json_serializable: ^6.6.1
  dio: ^5.1.1
  built_value: ^8.4.4

dev_dependencies:
  retrofit_generator: ^6.0.0+3
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/locations.json

